apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ${IMAGE_URL}
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_USER
              value: ${DATABASE_USER}
            - name: DATABASE_PASSWORD
              value: ${DATABASE_PASSWORD}
            - name: DATABASE_NAME
              value: ${DATABASE_NAME}
            - name: DATABASE_HOST
              value: ${DATABASE_HOST}
            - name: DATABASE_PORT
              value: "5432"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000  
  type: LoadBalancer  